In [1]:
import numpy as np
import pandas as pd
import lightgbm as lgb

In [5]:
X_train = pd.read_csv("X_train.csv", index_col=0)
y_train = pd.read_csv("y_train.csv", index_col=0)

In [27]:
aDict = {"A": ["Exhibit Hall A1"]}

In [40]:
roomClassif = pd.read_csv("Rooms.csv")
e = [0,1,2,40,41,42,43,44,106,107, 108, 109, 143, 23, 24,87]
a = [39, 122, 123]
b = [102,103,104,105,137,138,139]

In [41]:
roomClassif

,RoomID,Name,Sqft,Cost,Building,Floor,X,Y
0,0,Exhibit Hall A1,149000,2859.00,0,0,1.0,1
1,1,Exhibit Hall A2,86000,2204.77,0,0,2.0,1
2,2,Exhibit Hall A3,105000,3025.11,0,0,3.0,1
3,3,Exhibit Hall Meeting Room A101,7667,192.10,0,0,3.0,1
4,4,Exhibit Hall Meeting Room A102,7667,192.10,0,0,3.0,2
5,5,Exhibit Hall Meeting Room A103,7667,192.10,0,0,3.0,3
6,6,Meeting Room A301,2863,82.16,0,60,1.0,2
7,7,Meeting Room A302,4239,120.38,0,60,2.0,1
8,8,Meeting Room A303,1331,40.18,0,60,3.0,1
9,9,Meeting Room A304,1331,37.65,0,60,3.0,2
10,10,Meeting Room A305,4272,125.68,0,60,2.0,2
11,11,Meeting Room A306,534,12.38,0,60,1.0,3
12,12,Meeting Room A307,1897,53.64,0,60,8.0,4
13,13,Meeting Room A308a,454,12.50,0,60,9.0,4
14,14,Meeting Room A308b,486,13.39,0,60,10.0,4
15,15,Meeting Room A309,1897,52.73,0,60,13.0,4
16,16,Meeting Room A310,950,28.11,0,60,13.0,2
17,17,Meeting Room A311,2647,81.73,0,60,9.0,1
18,18,Meeting Room A312,2625,80.26,0,60,8.0,1
19,19,Meeting Room A313,2386,82.16,0,60,7.0,1
20,20,Meeting Room A314,2561,88.19,0,60,6.0,1
21,21,Meeting Room A315,1812,58.32,0,60,5.0,2
22,22,Meeting Room A316,1816,58.45,0,60,5.0,1
23,23,Building A Registration Hall,10162,285.24,0,90,3.0,6
24,24,Building A-B Registration Hall,20324,639.17,0,90,3.0,6
25,25,Executive Boardroom,2593,120.38,0,90,1.0,4
26,26,Meeting Room A401,1220,65.38,0,90,4.0,4
27,27,Meeting Room A402,1898,120.05,0,90,5.0,4
28,28,Meeting Room A403,1901,82.54,0,90,6.0,4
29,29,Meeting Room A404,4096,72.72,0,90,7.0,4
...,...,...,...,...,...,...,...,...
114,114,Meeting Room C103,1360,6.66,260,0,1.0,9
115,115,Meeting Room C104,1164,29.07,260,0,1.0,8
116,116,Meeting Room C105,1781,27.09,260,0,1.0,7
117,117,Meeting Room C106,1779,83.15,260,0,1.0,6
118,118,Meeting Room C107,2391,37.85,260,0,1.0,5
119,119,Meeting Room C108,1779,58.80,260,0,1.0,4
120,120,Meeting Room C109,1719,83.70,260,0,1.0,3
121,121,Meeting Room C110,2328,38.71,260,0,1.0,2
122,122,Room C101 Auditorium,5163,119.15,260,0,1.0,12
123,123,Room C102 Auditorium,2420,45.27,260,0,2.0,11
124,124,Meeting Room C201,2342,50.40,260,30,1.0,7
125,125,Meeting Room C202,1610,124.52,260,30,1.0,6
126,126,Meeting Room C203,2105,465.15,260,30,1.0,5
127,127,Meeting Room C204,1610,247.87,260,30,1.0,4
128,128,Meeting Room C205,2344,393.86,260,30,1.0,3
129,129,Meeting Room C206,2614,112.86,260,30,1.0,1
130,130,Meeting Room C207,1592,254.76,260,30,2.0,1
131,131,Meeting Room C208,1430,157.87,260,30,3.0,1
132,132,Meeting Room C209,1488,136.02,260,30,4.0,1
133,133,Meeting Room C210,1430,78.65,260,30,5.0,1
134,134,Meeting Room C211,1430,75.98,260,30,6.0,1
135,135,Meeting Room C212,1488,51.94,260,30,7.0,1
136,136,Meeting Room C213,1430,32.14,260,30,8.0,1
137,137,Georgia Ballroom 1,7685,439.49,260,60,1.0,3
138,138,Georgia Ballroom 2,10378,626.76,260,60,1.0,2
139,139,Georgia Ballroom 3,7685,471.15,260,60,1.0,1
140,140,Meeting Room C301,2288,181.93,260,60,2.0,5
141,141,Meeting Room C302,3275,245.18,260,60,3.0,6
142,142,Meeting Room A308,940,25.89,0,60,9.5,4
143,143,Exhibit Hall BC,85300,1640.00,260,0,5.0,0

In [43]:
E_A = 0
E_B = 0
E_C = 0
M_A = 0
M_B = 0
M_C = 0
if len(aDict)>0:
        for bldg in aDict.keys():
            print(bldg)
            for room in aDict[bldg]:
                print(room)
                roomId = roomClassif[roomClassif["Name"]==room]["RoomID"].values[0]
                print(cat)
                if bldg=="A" and roomId in e:
                    E_A += 1
                elif bldg=="B" and roomId in e:
                    E_B += 1 
                elif bldg=="C" and roomId in e:
                    E_C += 1
                if bldg=="A" and (roomId not in e and roomId not in a and roomId not in b):
                    M_A += 1
                elif bldg=="B" and (roomId not in e and roomId not in a and roomId not in b):
                    M_B += 1 
                elif bldg=="C" and (roomId not in e and roomId not in a and roomId not in b):
                    M_C += 1

A
Exhibit Hall A1
E-A3

In [45]:
X_train

NameError: name 'X_train' is not defined

In [46]:
pd.DataFrame({"A": 1, "B": 2})

ValueError: If using all scalar values, you must pass an index

In [4]:
pd.read_csv("roomClassif.csv")

                         Space Name Category
0           A-B Connector Concourse      NaN
1                   Exhibit Hall A1     E-A3
2                   Exhibit Hall A2     E-A1
3                   Exhibit Hall A3     E-A2
4    Exhibit Hall Meeting Room A101     M-A5
5    Exhibit Hall Meeting Room A102     M-A5
6    Exhibit Hall Meeting Room A103     M-A5
7                 Meeting Room A301     M-A2
8                 Meeting Room A302     M-A4
9                 Meeting Room A303     M-A1
10                Meeting Room A304     M-A1
11                Meeting Room A305     M-A4
12                Meeting Room A306     M-A1
13                Meeting Room A307     M-A1
14               Meeting Room A308a     M-A1
15               Meeting Room A308b     M-A1
16                Meeting Room A309     M-A1
17                Meeting Room A310     M-A1
18                Meeting Room A311     M-A2
19                Meeting Room A312     M-A2
20                Meeting Room A313     M-A2
21                Meeting Room A314     M-A2
22                Meeting Room A315     M-A1
23                Meeting Room A316     M-A1
24     Building A Registration Hall      P-A
25   Building A-B Registration Hall      P-A
26              Executive Boardroom     M-A2
27                Meeting Room A401     M-A1
28                Meeting Room A402     M-A1
29                Meeting Room A403     M-A1
..                              ...      ...
969                             NaN      NaN
970                             NaN      NaN
971                             NaN      NaN
972                             NaN      NaN
973                             NaN      NaN
974                             NaN      NaN
975                             NaN      NaN
976                             NaN      NaN
977                             NaN      NaN
978                             NaN      NaN
979                             NaN      NaN
980                             NaN      NaN
981                             NaN      NaN
982                             NaN      NaN
983                             NaN      NaN
984                             NaN      NaN
985                             NaN      NaN
986                             NaN      NaN
987                             NaN      NaN
988                             NaN      NaN
989                             NaN      NaN
990                             NaN      NaN
991                             NaN      NaN
992                             NaN      NaN
993                             NaN      NaN
994                             NaN      NaN
995                             NaN      NaN
996                             NaN      NaN
997                             NaN      NaN
998                             NaN      NaN

[999 rows x 2 columns]

In [18]:
X_train

,sqftPerEvent,orderedRentTotal,Attendance,totalRoomNights,eventDuration,contactTillStart,M-B,E-A,E-B,E-C,M-A,M-C,FB
558,5625501,190430.00,27000,3200.0,3,1607,0,0,3,7,0,23,1.00
557,7666913,201286.00,17000,20000.0,3,2340,47,3,6,0,20,0,75000.00
556,4794000,100000.00,300,1.0,1,88,0,3,3,1,0,0,2000.00
555,1671020,51500.00,15000,1350.0,3,689,0,0,0,5,0,8,1.00
554,1348840,0.00,1600,2220.0,6,295,0,2,0,0,30,0,450000.00
553,823000,20500.00,48000,1.0,2,1447,0,0,0,2,0,0,0.01
552,6171,1723.00,500,1.0,1,175,2,0,0,0,0,0,1.00
551,119558,35987.64,1000,100.0,4,211,0,0,0,0,5,0,1.00
550,2909311,88000.00,2500,3310.0,3,1031,0,3,0,0,16,0,1.00
548,13244374,540000.00,47000,37848.0,3,1151,47,7,10,13,29,23,200000.00
547,4544053,0.00,4837,8568.0,3,300,47,0,0,3,0,26,850000.00
546,2404552,185520.60,5950,9200.0,3,1734,0,2,0,0,33,0,250000.00
545,221368,10000.00,950,1.0,1,132,0,1,0,0,5,0,20000.00
544,4459303,152925.00,6603,21240.0,5,2265,47,0,4,0,25,0,350000.00
542,204660,36500.00,3000,1.0,1,353,0,0,0,0,0,7,1.00
543,1238850,28668.00,5500,1.0,2,345,0,3,0,0,1,0,1.00
541,1850433,56077.00,80000,1.0,6,236,0,0,0,5,0,5,1.00
540,109972,13500.00,700,475.0,3,321,0,0,0,0,16,0,1.00
539,2598017,135000.00,39000,7042.0,4,2012,0,4,1,0,30,0,1.00
538,14924101,240522.51,41,12000.0,3,2199,51,1,8,14,0,23,1750000.00
537,2048,100.00,35,1.0,1,36,0,0,0,0,1,0,1550.00
536,26922,8000.00,1800,1.0,1,268,0,0,0,0,4,0,1.00
535,16435,5100.00,700,1.0,1,53,0,0,0,0,0,0,1.00
534,16435,5100.00,1700,1.0,1,112,0,0,0,0,0,0,1.00
533,4008698,128000.00,4500,5237.0,3,1639,0,3,0,0,30,0,50000.00
532,34489,7650.00,1500,1.0,2,127,1,0,0,0,0,0,500.00
531,436080,67000.00,400,2468.0,4,276,14,0,0,0,0,0,56000.00
530,21340,6673.10,60,1.0,6,17,0,0,0,0,0,3,1.00
529,27191,15300.00,1000,150.0,1,355,0,0,0,0,0,0,1.00
528,36866,12000.00,803,1.0,3,113,0,0,0,0,1,0,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,194815,9720.00,5300,0.0,2,146,1,0,2,0,0,0,0.00
149,5050812,332800.00,50000,1.0,5,1387,0,0,0,4,0,8,0.00
150,12643,1161.00,250,0.0,1,75,0,0,0,0,0,2,0.00
148,7685,3605.00,415,1.0,1,329,0,0,0,0,0,0,0.00
147,69649,12870.00,1284,0.0,8,118,0,0,0,0,2,0,0.00
146,10211752,370300.00,15000,19900.0,3,1402,47,0,6,0,0,0,0.01
145,170424,34900.00,1500,1.0,3,462,0,0,0,0,3,0,0.00
144,244728,28690.00,2000,0.0,3,408,0,0,0,0,0,9,0.00
143,3362064,84952.75,5417,13320.0,4,1443,50,0,4,0,0,0,100000.00
141,6015598,219050.00,7628,16415.0,3,1424,0,0,0,8,0,23,0.00
140,4354303,110800.00,6399,6680.0,3,1462,0,4,0,0,30,0,0.00
142,303600,10000.00,40,0.0,1,36,0,0,1,0,0,0,0.00
138,2140000,117500.00,39483,1.0,1,1368,0,0,3,0,0,0,0.00
137,607200,9500.00,5856,0.0,1,149,0,0,1,0,0,0,0.00
135,501901,0.00,1650,0.0,3,376,0,3,0,0,21,0,210000.00
134,179974,15000.00,300,0.0,1,18,0,1,0,1,0,0,0.00
133,9086047,439810.00,68000,20000.0,2,1149,47,4,6,2,29,23,0.00
132,371000,18181.25,150,0.0,136,141,7,0,0,0,0,8,0.00
131,589088,37220.00,2000,0.0,2,278,0,2,0,0,23,0,80000.00
129,268500,18000.00,3000,0.0,2,473,0,0,1,0,0,0,0.00
128,3243745,181200.00,42865,3200.0,3,822,0,0,0,7,0,23,0.00
130,74973,9528.00,1700,1.0,1,362,0,0,0,0,3,0,0.00
127,1293519,45000.00,5777,0.0,3,112,5,0,1,0,0,0,0.00
126,551171,20425.00,4000,1.0,3,1372,0,1,0,0,5,0,0.00
125,213210,0.00,600,250.0,2,313,10,0,0,0,0,0,110000.00
124,1368111,18881.00,1429,0.0,6,603,0,1,0,0,4,0,0.00
123,135352,0.00,880,0.0,2,349,0,2,0,0,10,0,70000.00
122,962588,52000.00,24000,0.0,3,128,0,2,0,0,1,0,0.00
121,15781964,700000.00,31649,1.0,3,1334,47,1,5,9,30,22,0.00
120,1044175,124074.50,49340,1.0,1,1349,2,0,0,0,0,0,0.00

In [9]:
lgbParams = {'subsample': 0.36000000000000004,
                    'reg_lambda': 0.7100000000000001,
                    'reg_alpha': 0.9,
                    'objective': 'regression_l1',
                    'num_leaves': 29,
                    'min_child_weight': 0.0001,
                    'max_depth': 10,
                    'learning_rate': 0.1,
                    'boosting': 'gbdt',
                    'n_estimators': (330+93+43)/3}
lgbr = lgb.LGBMRegressor(**lgbParams)
lgbr.fit(X_train, y_train)

TypeError: 'float' object cannot be interpreted as an integer